### ISSUE TITLE
browser-android-tabs failing to build using provided instructions

### ISSUE THREAD

**Issue by ericdunbar** [brave/browser-android-tabs#1372]
## Description 
The github-provided instructions for building android-browser-tabs [(android-browser-tabs)](https://github.com/brave/browser-android-tabs) do not lead to a successful build as of March, 2019.

First, running `sh scripts/getThirdParties.js` fails on a few occasions with _FileNotFoundError_ for _src/third_party/node/linux/node-linux-x64.tar.gz.sha1_ or _ERROR:root:Git error: rc=0, output=''_.

Second, `ninja -C out/Default chrome_public_apk` fails with the following error:

_ninja: Entering directory `out/Default'
ninja: error: '../../node_modules/brave-ui/package.json', needed by 'gen/android-brave/web-ui-brave_rewards_settings/brave_rewards_settings.grd', missing and no known rule to make it_

PS Note that the backquote (`) before out/Default is present in the output. Could that be the source of problems?

## Steps to reproduce 

   1. Follow instructions at [https://github.com/brave/browser-android-tabs](https://github.com/brave/browser-android-tabs)
     i. On fresh install of Ubuntu 18.04 `sudo apt install python` to ensure a compatible version of python (2.7?) is installed
     ii. Download Node 10.15.3 LTS from provided link and add directory to path (in .bashrc)
     iii. Download and build ninja and then add directory to path
     iv. Add depot_tools to path
   2. Execute `sh scripts/getThirdParties.js`
   3. Execute `ninja -C out/Default chrome_public_apk`

## Actual result 
**Sample sh scripts/getThirdParties.js output of the errors:**

Running hooks:  22% (18/81) lastchange    
________ running '/usr/bin/python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/home/rd/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  23% (19/81) gpu_lists_version
________ running '/usr/bin/python src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h' in '/home/rd/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  28% (23/81) gn_linux64       
________ running '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --no_auth --bucket chromium-gn -s src/buildtools/linux64/gn.sha1' in '/home/rd/browser-android-tabs'

0> Downloading src/v8/test/fuzzer/wasm_corpus.tar.gz...
0> Extracting 15291 entries from src/v8/test/fuzzer/wasm_corpus.tar.gz to src/v8/test/fuzzer/wasm_corpus
Downloading 1 files took 8.981160 second(s)
Running hooks:  48% (39/81) node_linux64
________ running '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' in '/home/rd/browser-android-tabs'
Traceback (most recent call last):
  File "src/third_party/depot_tools/download_from_google_storage.py", line 606, in <module>
    sys.exit(main(sys.argv))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 602, in main
    options.extract)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 390, in download_from_google_storage
    auto_platform))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 166, in enumerate_input
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: src/third_party/node/linux/node-linux-x64.tar.gz.sha1 not found.
Error: Command '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' returned non-zero exit status 1 in /home/rd/browser-android-tabs
Running hooks:  22% (18/81) lastchange    
________ running '/usr/bin/python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/home/rd/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  23% (19/81) gpu_lists_version
________ running '/usr/bin/python src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h' in '/home/rd/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  48% (39/81) node_linux64        
________ running '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' in '/home/rd/browser-android-tabs'
Traceback (most recent call last):
  File "src/third_party/depot_tools/download_from_google_storage.py", line 606, in <module>
    sys.exit(main(sys.argv))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 602, in main
    options.extract)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 390, in download_from_google_storage
    auto_platform))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 166, in enumerate_input
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: src/third_party/node/linux/node-linux-x64.tar.gz.sha1 not found.
Error: Command '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' returned non-zero exit status 1 in /home/rd/browser-android-tabs
Running as non-root user.
You might have to enter your password one or more times for 'sudo'.

Skipping debugging symbols.
Including 32-bit libraries.
Skipping ARM cross toolchain.
Skipping NaCl, NaCl toolchain, NaCl ports dependencies.
[sudo] password for rrd: 

**all ninja output:**
rrd@rrd-HP-ProBook-6460b:~/browser-android-tabs/src$ ninja -C out/Default chrome_public_apk
ninja: Entering directory `out/Default'
ninja: error: '../../node_modules/brave-ui/package.json', needed by 'gen/android-brave/web-ui-brave_rewards_settings/brave_rewards_settings.grd', missing and no known rule to make it

## Expected result
Build success

## Issue reproduces how often 
Every time this has been attempted (on a variety of laptops).

## Issue happens on 

Current github repository checkout (as of 2019/03/21): base-72.0.3626.121

## Device details
I'm building this on Ubuntu 18.04 LTS v2 with Node 10.15.3 LTS (binary download) and ninja 1.90 built from source.

8 GB RAM, 110 GB free HDD, older i5 laptop CPU

### Additional information
I've found three other github issues that relate, two open and one closed addressed by SergeyZhukovsky.

These are my search terms: 
is:issue is:open FileNotFoundError node-linux-x64.tar.gz.sha1 
is:issue is:open ninja package.json

[ yarn run couldn't find a package.json file while running getThirdParties.js #204](https://github.com/brave/browser-android-tabs/issues/204) 
[ Failed to download third party dependencies #216 ](https://github.com/brave/browser-android-tabs/issues/216)
[ Git is corrupt and isn't buildable at all #243](https://github.com/brave/browser-android-tabs/issues/243) 

Note: I have not tried these suggestions from 2017 yet. I'm also going to see if I can get Chromium for Android to build (is it ever big... 12 GB and I'm already at the 80 minute mark). If that can build then it's not my system but Brave :).

**Comment by ericdunbar** [comment]
Update: After 12 hours of building I successfully built chromium as per https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md

My setup is capable of building chromium so I imagine it ought to _also_ be able to do brave.

**Comment by yachtcaptain23** [comment]
Hey Eric, thanks for taking the approaches to contributing. `sh scripts/getThirdParties.js` needs to succeed for the build to work. I would make sure both `npm` and `yarn` are installed on your machine.

Additionally, I believe `autoninja -C out/Default chrome_public_apk` will help you build faster than simply `ninja -C out/Default chrome_public_apk`. This command checks to see how many cores you have and sets it to that number.

**Comment by n0tty** [comment]
Your error is caused because gsync fails to download nodejs, and eventhough you might have downloaded nodejs and npm, after you run the  sh scripts/getThirdParties.js command, gsync will break the node package and npm will be unavailable. This will result in npm install command to not work and the final build to not have node_modules. 
While I pushed the required file to successfully build the script, you can also install the node modules by simply doing npm install on the src dir.

**Comment by n0tty** [comment]
The fix for second part to this issue - npm removal due to libssl-dev and libssl1.0-dev conflict has been identified and install instructions have been pushed by me. I have not tried the older versions of ubuntu, but in Ubuntu 18.04 this is definitely a problem when you try to install npm from aptitude.
https://github.com/brave/browser-android-tabs/pull/1500

**Comment by n0tty** [comment]
The following error **ERROR:root:Git error: rc=0, output=''** occurs on 2 or 3 version checks. However, there is no build failures that seem to be triggered by this.

**Comment by caffaware** [comment]
I'm having the same issue, below is my output. Did you find a solution to this ? I've managed to compile chromium for Android but I would like to compile Brave instead.

x@x:~/codebases/browser-android-tabs/src$ sh scripts/getThirdParties.js
Syncing projects: 100% (240/240), done.                                                                                                                                    
Running hooks:  21% (18/83) lastchange    
________ running '/usr/bin/python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/home/x/codebases/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  22% (19/83) gpu_lists_version
________ running '/usr/bin/python src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h' in '/home/x/codebases/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  46% (39/83) node_linux64        
________ running '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' in '/home/x/codebases/browser-android-tabs'
Traceback (most recent call last):
  File "src/third_party/depot_tools/download_from_google_storage.py", line 606, in <module>
    sys.exit(main(sys.argv))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 602, in main
    options.extract)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 390, in download_from_google_storage
    auto_platform))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 166, in enumerate_input
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: src/third_party/node/linux/node-linux-x64.tar.gz.sha1 not found.
Error: Command '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' returned non-zero exit status 1 in /home/x/codebases/browser-android-tabs
Running hooks:  21% (18/83) lastchange    
________ running '/usr/bin/python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/home/x/codebases/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  22% (19/83) gpu_lists_version
________ running '/usr/bin/python src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h' in '/home/x/codebases/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  46% (39/83) node_linux64        
________ running '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' in '/home/x/codebases/browser-android-tabs'
Traceback (most recent call last):
  File "src/third_party/depot_tools/download_from_google_storage.py", line 606, in <module>
    sys.exit(main(sys.argv))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 602, in main
    options.extract)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 390, in download_from_google_storage
    auto_platform))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 166, in enumerate_input
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: src/third_party/node/linux/node-linux-x64.tar.gz.sha1 not found.
Error: Command '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' returned non-zero exit status 1 in /home/x/codebases/browser-android-tabs
Running as non-root user.
You might have to enter your password one or more times for 'sudo'.

Skipping debugging symbols.
Including 32-bit libraries.
Skipping ARM cross toolchain.
Skipping NaCl, NaCl toolchain, NaCl ports dependencies.
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://be.archive.ubuntu.com/ubuntu bionic InRelease                                                                       
Hit:3 http://linux.teamviewer.com/deb stable InRelease                                                                           
Hit:4 http://be.archive.ubuntu.com/ubuntu bionic-updates InRelease                                         
Hit:5 http://be.archive.ubuntu.com/ubuntu bionic-backports InRelease                                       
Hit:6 https://download.sublimetext.com apt/stable/ InRelease                         
Reading package lists... Done                      
Finding missing packages...
Packages required:  libpci3:i386 libx11-xcb1:i386 linux-libc-dev:i386 apache2-bin binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf binutils-mips64el-linux-gnuabi64 binutils-mipsel-linux-gnu bison bzip2 cdbs curl dbus-x11 devscripts dpkg-dev elfutils fakeroot flex g++ g++-7-multilib git-core git-svn gperf lib32gcc1 lib32stdc++6 libapache2-mod-php7.2 libappindicator3-1 libappindicator3-dev libasound2 libasound2-dev libatk1.0-0 libatspi2.0-0 libatspi2.0-dev libbluetooth-dev libbrlapi0.6 libbrlapi-dev libbz2-1.0 libbz2-dev libc6 libc6-i386 libcairo2 libcairo2-dev libcap2 libcap-dev libcups2 libcups2-dev libcurl4-gnutls-dev libdrm-dev libelf-dev libexpat1 libffi6 libffi-dev libfontconfig1 libfreetype6 libgbm-dev libglib2.0-0 libglib2.0-dev libglu1-mesa-dev libgnome-keyring0 libgnome-keyring-dev libgtk-3-0 libgtk-3-dev libjpeg-dev libkrb5-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libpam0g libpam0g-dev libpango1.0-0 libpci3 libpci-dev libpcre3 libpixman-1-0 libpng16-16 libpulse0 libpulse-dev libsctp-dev libspeechd2 libspeechd-dev libsqlite3-0 libsqlite3-dev libssl-dev libstdc++6 libudev1 libudev-dev libuuid1 libwayland-egl1-mesa libwww-perl libx11-6 libx11-xcb1 libxau6 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxinerama1 libxkbcommon-dev libxrandr2 libxrender1 libxslt1-dev libxss-dev libxt-dev libxtst6 libxtst-dev locales openbox p7zip patch perl php7.2-cgi pkg-config python python-cherrypy3 python-crypto python-dev python-numpy python-opencv python-openssl python-psutil python-yaml rpm ruby subversion uuid-dev wdiff x11-utils xcompmgr xz-utils zip zlib1g

No missing packages, and the packages are up to date.

Skipping installation of Chrome OS fonts.
Installing locales.
Locales already up-to-date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
lib32z1 is already the newest version (1:1.2.11.dfsg-0ubuntu2).
x11-utils is already the newest version (7.7+3build1).
lighttpd is already the newest version (1.4.45-1ubuntu3).
python-pexpect is already the newest version (4.2.1-1).
xvfb is already the newest version (2:1.19.6-1ubuntu4.2).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g:i386 is already the newest version (1:1.2.11.dfsg-0ubuntu2).
libncurses5:i386 is already the newest version (6.1-1ubuntu1.18.04).
libstdc++6:i386 is already the newest version (8.3.0-6ubuntu1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bsdiff is already the newest version (4.3-20).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
install-build-deps-android.sh complete.
Syncing projects: 100% (240/240), done.                                                                                                                                    
Running hooks:  21% (18/83) lastchange    
________ running '/usr/bin/python src/build/util/lastchange.py -o src/build/util/LASTCHANGE' in '/home/x/codebases/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  22% (19/83) gpu_lists_version
________ running '/usr/bin/python src/build/util/lastchange.py -m GPU_LISTS_VERSION --revision-id-only --header src/gpu/config/gpu_lists_version.h' in '/home/x/codebases/browser-android-tabs'
ERROR:root:Git error: rc=0, output=''
Running hooks:  46% (39/83) node_linux64        
________ running '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' in '/home/x/codebases/browser-android-tabs'
Traceback (most recent call last):
  File "src/third_party/depot_tools/download_from_google_storage.py", line 606, in <module>
    sys.exit(main(sys.argv))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 602, in main
    options.extract)
  File "src/third_party/depot_tools/download_from_google_storage.py", line 390, in download_from_google_storage
    auto_platform))
  File "src/third_party/depot_tools/download_from_google_storage.py", line 166, in enumerate_input
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: src/third_party/node/linux/node-linux-x64.tar.gz.sha1 not found.
Error: Command '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --no_resume --extract --no_auth --bucket chromium-nodejs/8.9.1 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' returned non-zero exit status 1 in /home/x/codebases/browser-android-tabs
scripts/updateSubModules.js: 6: scripts/updateSubModules.js: npm: not found
scripts/updateSubModules.js: 7: scripts/updateSubModules.js: npm: not found
scripts/updateSubModules.js: 10: scripts/updateSubModules.js: npm: not found
scripts/updateSubModules.js: 11: scripts/updateSubModules.js: npm: not found
scripts/getThirdParties.js: 12: scripts/getThirdParties.js: npm: not found
Waiting for editor on "/home/x/codebases/browser-android-tabs/src/out/Default/args.gn"...
Generating files...
Done. Made 21908 targets from 1676 files in 5153ms

**Comment by caffaware** [comment]
I've managed to solve it by installing node from source by following these instructions: https://websiteforstudents.com/install-the-latest-node-js-and-nmp-packages-on-ubuntu-16-04-18-04-lts/ after this the getThirdParties.js script runs fine and I can build
