### ISSUE TITLE
Opening a new tab logs errors 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1802]
## Description 
Opening a new tab logs errors 

## Steps to reproduce 

   1. Clean install playstore build
   2. Open a new tab via tab manager or via kabob menu
   3. Console logs errors

## Actual result 
```
2019-07-02 14:41:07.109 24290-24290/? E/cr_BkgrdTaskSchedulerJS: BackgroundTask class org.chromium.chrome.browser.omaha.OmahaService has no parameterless public constructor.
2019-07-02 14:41:10.110 24290-24290/? W/View: requestLayout() improperly called by org.chromium.chrome.browser.compositor.CompositorViewHolder{f8e28d V.E...... ......ID 0,0-1440,2621 #7f0b0165 app:id/compositor_view_holder} during layout: running second layout pass
2019-07-02 14:41:10.110 24290-24290/? W/View: requestLayout() improperly called by org.chromium.chrome.browser.ntp.NewTabPageView{65ff5d7 V.E...... ......ID 0,0-1440,2621} during layout: running second layout pass
2019-07-02 14:41:36.087 24290-24290/? W/cr_NewTabPage: Bad data found for NewTabPageScrollPosition : null
    java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:577)
        at java.lang.Integer.parseInt(Integer.java:650)
        at rqb.a(PG:12)
        at rqb.<init>(PG:23)
        at Xob.a(PG:6)
        at Zob.a(PG:20)
        at org.chromium.chrome.browser.tab.Tab.a(PG:142)
        at org.chromium.chrome.browser.tab.Tab.a(PG:71)
        at DNb.a(PG:98)
        at DNb.a(PG:3)
        at DNb.a(PG:24)
        at DNb.a(PG:20)
        at TNb.b(PG:2)
        at org.chromium.chrome.browser.ChromeTabbedActivity.gc(PG:2)
        at ICa.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-07-02 14:41:36.104 1170-1188/? I/ActivityManager: Start proc 26322:com.brave.browser:sandboxed_process5/u0i24 for service com.brave.browser/org.chromium.content.app.SandboxedProcessService5
2019-07-02 14:41:36.433 26322-26336/? I/chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
```
## Expected result
No error

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? N/A

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Google Pixel 3XL
   - Android version: 9.0
   
## Brave version
1.0.99 GPS version

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
This is reproducible on ads 5 build as well
