### ISSUE TITLE
Brave Rewards wallet generation hangs forever

### ISSUE THREAD

**Issue by kravietz** [brave/browser-android-tabs#1865]
## Description 
When trying to join Brave Rewards the Creating Wallet button spins indefinitely.

## Steps to reproduce 

   1. Open **Brave Rewards** tab
   2. Click **Yes, I'm ready**
   3. Watch **Creating Wallet** spinner forever

## Actual result 
Wallet not created.

## Expected result
Wallet created in finite time.

## Issue reproduces how often 

Easily reproduced (always).

## Issue happens on 
   - Current Play Store version? **yes**
   - Beta build? **no**

## Device details
   - Install type (ARM, x86): **ARM**
   - Device (Phone, Tablet, Phablet): **Phone**
   - Android version: **9**
   
## Brave version
1.1.1

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? **no**
- Is the issue reproducible on the latest version of Chrome? **no** (seems to be exclusive to Rewards)

### Additional information
This is [LineageOS for MicroG](https://lineage.microg.org/) distribution with no Google Play Services. On `logcat` the following messages can be seen which seems to suggest that Brave is trying to connect to Google SafetyNet (which is not a good idea in an app that promotes privacy).

```
07-18 09:18:20.884  7448  7501 E chromium: [ERROR:rewards_service_impl.cc(192)] Failed to read file: /data/user/0/com.brave.browser/app_chrome/Default/ledger_state
07-18 09:18:20.935  7536  7567 E chromium: [ERROR:ledger_impl.cc(377)] Failed to initialize wallet
07-18 09:18:20.998   663   663 D QCOM PowerHAL: LAUNCH HINT: OFF
07-18 09:18:21.841  7448  7477 I cr_BindingManager: Moderate binding enabled: maxSize=40
07-18 09:18:24.403 26455 26455 D GmsSafetyNetClientSvc: onBind: Intent { act=com.google.android.gms.safetynet.service.START pkg=com.google.android.gms }
07-18 09:18:24.428 26455  3613 D SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-18 09:18:24.428 26455  3613 D SafeParcel: Unknown field num 11 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-18 09:18:24.428 26455  3613 D SafeParcel: Unknown field num 12 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
07-18 09:18:24.428 26455  3613 D GmsSafetyNetClientSvc: bound by: GetServiceRequest{serviceId=SAFETY_NET_CLIENT, gmsVersion=12451000, packageName='com.brave.browser', extras=Bundle[{}]}
07-18 09:18:25.121 24690 27742 W ActivityManager: Unable to start service Intent { act=org.microg.gms.droidguard.REMOTE pkg=org.microg.gms.droidguard } U=0: not found
07-18 09:18:25.125  7448  7448 E cr_SafetyNetCheck: Failed to perform SafetyNetCheck: RC: 14
```

**Comment by kravietz** [comment]
Installing [microG DroidGuard Helper](https://microg.org/download.html) seems to resolve the freeze but then Brave just displays this message:

> We're sorry it appears Brave Rewards is not available on your device

And there are these messages in `logcat`:

```
07-18 09:23:36.256 26455 11342 D GmsSafetyNetClientSvc: bound by: GetServiceRequest{serviceId=SAFETY_NET_CLIENT, gmsVersion=12451000, packageName='com.brave.browser', extras=Bundle[{}]}
07-18 09:23:37.004 24690 24707 I ActivityManager: Start proc 8129:com.google.android.gms.unstable/u0a162 for service org.microg.gms.droidguard/.RemoteDroidGuardService
07-18 09:23:37.114  8129  8145 W GmsDroidguardHelper: 
07-18 09:23:37.114  8129  8145 W GmsDroidguardHelper: java.lang.NoSuchFieldException: BUILD
07-18 09:23:37.114  8129  8145 W GmsDroidguardHelper: 	at java.lang.Class.getField(Class.java:1601)
07-18 09:23:37.114  8129  8145 W GmsDroidguardHelper: 	at org.microg.gms.droidguard.DroidguardHelper.createSystemInfoPair(DroidguardHelper.java:169)
07-18 09:23:37.114  8129  8145 W GmsDroidguardHelper: 	at org.microg.gms.droidguard.DroidguardHelper.getSystemInfo(DroidguardHelper.java:117)
07-18 09:23:37.114  8129  8145 W GmsDroidguardHelper: 	at org.microg.gms.droidguard.DroidguardHelper.guard(DroidguardHelper.java:64)
07-18 09:23:37.114  8129  8145 W GmsDroidguardHelper: 	at org.microg.gms.droidguard.RemoteDroidGuardService$1$1.run(RemoteDroidGuardService.java:23)
07-18 09:23:37.114  8129  8145 W GmsDroidguardHelper: 	at java.lang.Thread.run(Thread.java:764)
07-18 09:23:37.124  8129  8145 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-18 09:23:37.132  8129  8145 D GmsDroidguardHelper: -- Request --
07-18 09:23:37.132  8129  8145 D GmsDroidguardHelper: DGRequest{usage=DGUsage{type=attest, packageName=com.google.android.gms}, info=[KeyValuePair{key=BUILD, val=unknown}, KeyValuePair{key=BOARD, val=marlin}, KeyValuePair{key=BOOTLOADER, val=8996-012001-1812132253}, KeyValuePair{key=BRAND, val=google}, KeyValuePair{key=CPU_ABI, val=arm64-v8a}, KeyValuePair{key=CPU_ABI2, val=}, KeyValuePair{key=DEVICE, val=marlin}, KeyValuePair{key=DISPLAY, val=lineage_marlin-userdebug 9 PQ3A.190705.003 eng.root.20190709.145904 dev-keys}, KeyValuePair{key=FINGERPRINT, val=google/marlin/marlin:9/PQ3A.190705.001/5565753:user/release-keys}, KeyValuePair{key=HARDWARE, val=marlin}, KeyValuePair{key=HOST, val=ccf399309c7c}, KeyValuePair{key=ID, val=PQ3A.190705.003}, KeyValuePair{key=MANUFACTURER, val=Google}, KeyValuePair{key=MODEL, val=Pixel XL}, KeyValuePair{key=PRODUCT, val=marlin}, KeyValuePair{key=RADIO, val=8996-130281-1903110834}, KeyValuePair{key=SERIAL, val=HT73G0202240}, KeyValuePair{key=TAGS, val=dev-keys}, KeyValuePair{key=TIME, val=1562684316000}, KeyValuePair{key=TYPE, val=userdebug}, KeyValuePair{key=USER, val=root}, KeyValuePair{key=CODENAME, val=REL}, KeyValuePair{key=INCREMENTAL, val=eng.root.20190709.145904}, KeyValuePair{key=RELEASE, val=9}, KeyValuePair{key=SDK, val=28}, KeyValuePair{key=SDK_INT, val=28}], versionNamePrefix=9.6.83 (430-, isGoogleCn=false, enableInlineVm=true, cached=[], currentVersion=3, arch=aarch64}
07-18 09:23:37.475  8129  8145 D GmsDroidguardHelper: Using provided response data for /data/user/0/org.microg.gms.droidguard/app_dg_cache/19b362504df50a83d955d698aa510d1ce8fe8976.apk
07-18 09:23:37.480  8129  8138 W System  : A resource failed to call end. 
07-18 09:23:37.571  8149  8149 I dex2oat : The ClassLoaderContext is a special shared library.
07-18 09:23:37.571  8149  8149 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/org.microg.gms.droidguard/app_dg_cache/19b362504df50a83d955d698aa510d1ce8fe8976/the.apk --output-vdex-fd=42 --oat-fd=43 --oat-location=/data/user/0/org.microg.gms.droidguard/app_dg_cache/19b362504df50a83d955d698aa510d1ce8fe8976/oat/arm64/the.odex --compiler-filter=quicken --class-loader-context=&
07-18 09:23:37.849  8149  8149 I dex2oat : dex2oat took 281.908ms (83.335ms cpu) (threads: 4) arena alloc=4KB (4896B) java alloc=64KB (65744B) native alloc=812KB (831552B) free=2MB (2838464B)
07-18 09:23:37.876  8129  8145 I id.gms.unstabl: The ClassLoaderContext is a special shared library.
07-18 09:23:37.888  8129  8145 D ArtHook : Using: 64-bit ARM
07-18 09:23:37.892  8129  8145 W ArtHook : 
07-18 09:23:37.892  8129  8145 W ArtHook : java.lang.RuntimeException: Method has no artMethod field, is this a system running Art?
07-18 09:23:37.892  8129  8145 W ArtHook : 	at de.larma.arthook.ArtMethod.of(ArtMethod.java:115)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at de.larma.arthook.ArtMethod.of(ArtMethod.java:86)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at de.larma.arthook.ArtHook.hook(ArtHook.java:133)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at de.larma.arthook.ArtHook.hook(ArtHook.java:110)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at de.larma.arthook.ArtHook.hook(ArtHook.java:100)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at de.larma.arthook.ArtHook.hook(ArtHook.java:78)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at org.microg.gms.droidguard.SysHook.activate(SysHook.java:52)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at org.microg.gms.droidguard.DroidguardHelper.guard(DroidguardHelper.java:91)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at org.microg.gms.droidguard.RemoteDroidGuardService$1$1.run(RemoteDroidGuardService.java:23)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at java.lang.Thread.run(Thread.java:764)
07-18 09:23:37.892  8129  8145 W ArtHook : Caused by: java.lang.ClassNotFoundException: java.lang.reflect.AbstractMethod
07-18 09:23:37.892  8129  8145 W ArtHook : 	at java.lang.Class.classForName(Native Method)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at java.lang.Class.forName(Class.java:453)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at java.lang.Class.forName(Class.java:378)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at de.larma.arthook.ArtMethod.of(ArtMethod.java:111)
07-18 09:23:37.892  8129  8145 W ArtHook : 	... 9 more
07-18 09:23:37.892  8129  8145 W ArtHook : Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.reflect.AbstractMethod" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.microg.gms.droidguard-6-7cZDlQZ8F0ru96i1KL2w==/base.apk"],nativeLibraryDirectories=[/data/app/org.microg.gms.droidguard-6-7cZDlQZ8F0ru96i1KL2w==/lib/arm64, /system/fake-libs64, /data/app/org.microg.gms.droidguard-6-7cZDlQZ8F0ru96i1KL2w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
07-18 09:23:37.892  8129  8145 W ArtHook : 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-18 09:23:37.892  8129  8145 W ArtHook : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-18 09:23:37.892  8129  8145 W ArtHook : 	... 13 more
07-18 09:23:37.899  8129  8145 I chatty  : uid=10162(org.microg.gms.droidguard) Thread-2 identical 4 lines
07-18 09:23:37.900  8129  8145 W ArtHook : 
07-18 09:23:37.900  8129  8145 W ArtHook : java.lang.RuntimeException: Method has no artMethod field, is this a system running Art?
07-18 09:23:37.900  8129  8145 W ArtHook : 	at de.larma.arthook.ArtMethod.of(ArtMethod.java:115)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at de.larma.arthook.ArtMethod.of(ArtMethod.java:86)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at de.larma.arthook.ArtHook.hook(ArtHook.java:133)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at de.larma.arthook.ArtHook.hook(ArtHook.java:110)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at de.larma.arthook.ArtHook.hook(ArtHook.java:100)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at de.larma.arthook.ArtHook.hook(ArtHook.java:78)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at org.microg.gms.droidguard.SysHook.activate(SysHook.java:52)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at org.microg.gms.droidguard.DroidguardHelper.guard(DroidguardHelper.java:91)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at org.microg.gms.droidguard.RemoteDroidGuardService$1$1.run(RemoteDroidGuardService.java:23)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at java.lang.Thread.run(Thread.java:764)
07-18 09:23:37.900  8129  8145 W ArtHook : Caused by: java.lang.ClassNotFoundException: java.lang.reflect.AbstractMethod
07-18 09:23:37.900  8129  8145 W ArtHook : 	at java.lang.Class.classForName(Native Method)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at java.lang.Class.forName(Class.java:453)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at java.lang.Class.forName(Class.java:378)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at de.larma.arthook.ArtMethod.of(ArtMethod.java:111)
07-18 09:23:37.900  8129  8145 W ArtHook : 	... 9 more
07-18 09:23:37.900  8129  8145 W ArtHook : Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.reflect.AbstractMethod" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.microg.gms.droidguard-6-7cZDlQZ8F0ru96i1KL2w==/base.apk"],nativeLibraryDirectories=[/data/app/org.microg.gms.droidguard-6-7cZDlQZ8F0ru96i1KL2w==/lib/arm64, /system/fake-libs64, /data/app/org.microg.gms.droidguard-6-7cZDlQZ8F0ru96i1KL2w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
07-18 09:23:37.900  8129  8145 W ArtHook : 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-18 09:23:37.900  8129  8145 W ArtHook : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-18 09:23:37.900  8129  8145 W ArtHook : 	... 13 more
07-18 09:23:37.924  8129  8145 D GmsDroidguardHelper: b -> 4298820664973547449
07-18 09:23:37.957  8145  8145 W Thread-2: type=1400 audit(0.0:33497): avc: denied { read } for name="/" dev="tmpfs" ino=14289 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0
07-18 09:23:37.991  8145  8145 W Thread-2: type=1400 audit(0.0:33499): avc: denied { read } for name="modules" dev="proc" ino=4026532408 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc_modules:s0 tclass=file permissive=0
07-18 09:23:37.993  8129  8145 D GmsDroidguardHelper: b -> 4298820664973547449
07-18 09:23:37.997  8145  8145 W Thread-2: type=1400 audit(0.0:33500): avc: denied { read } for name="version" dev="proc" ino=4026532360 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0
07-18 09:23:38.107  8145  8145 W Thread-2: type=1400 audit(0.0:33504): avc: denied { read } for name="devices" dev="proc" ino=4026532426 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc:s0 tclass=file permissive=0
07-18 09:23:38.113  8129  8145 D GmsDroidguardHelper: c -> com.google.android.gms
07-18 09:23:38.304  8061  8096 E chromium: [ERROR:bat_client.cc(785)] Wallet creation didn't finish or corrupted. We need to clear persona Id and start again
07-18 09:23:38.503  8061  8096 V chromium: [VERBOSE1:ledger_impl.cc(1153)] 
07-18 09:23:38.503  8061  8096 V chromium: [ RESPONSE - registerPersonaSafetyNetCallback ]
07-18 09:23:38.503  8061  8096 V chromium: > time: 1563438218
07-18 09:23:38.503  8061  8096 V chromium: > result: Failure
07-18 09:23:38.503  8061  8096 V chromium: > response: {"statusCode":422,"error":"Unprocessable Entity","message":"Error unmarshalling body: No matching APK signing certificate found"}
07-18 09:23:38.503  8061  8096 V chromium: > headers accept-ranges: bytes
07-18 09:23:38.503  8061  8096 V chromium: > headers cache-control: no-cache
07-18 09:23:38.503  8061  8096 V chromium: > headers content-encoding: gzip
07-18 09:23:38.503  8061  8096 V chromium: > headers content-type: application/json; charset=utf-8
07-18 09:23:38.503  8061  8096 V chromium: > headers date: Thu, 18 Jul 2019 08:23:40 GMT
07-18 09:23:38.503  8061  8096 V chromium: > headers server: Cowboy
07-18 09:23:38.503  8061  8096 V chromium: > headers status: 422
07-18 09:23:38.503  8061  8096 V chromium: > headers vary: accept-encoding
07-18 09:23:38.503  8061  8096 V chromium: > headers via: 1.1 varnish
07-18 09:23:38.503  8061  8096 V chromium: > headers x-cache: MISS
07-18 09:23:38.503  8061  8096 V chromium: > headers x-cache-hits: 0
07-18 09:23:38.503  8061  8096 V chromium: > headers x-rate-limit-limit: 60
07-18 09:23:38.503  8061  8096 V chromium: > headers x-rate-limit-remaining: 59
07-18 09:23:38.503  8061  8096 V chromium: > headers x-rate-limit-reset: 1563438280
07-18 09:23:38.503  8061  8096 V chromium: > headers x-served-by: cache-lcy19266-LCY
07-18 09:23:38.503  8061  8096 V chromium: [ END RESPONSE ]
07-18 09:23:38.504  8061  8096 E chromium: [ERROR:ledger_impl.cc(377)] Failed to initialize wallet
```

**Comment by jjakob** [comment]
I have the same issue, also on LineageOS 14.1, but without any play services or Google apps (not even MicroG). It is a personal decision of mine to not use any Google services on my devices due to Google's politics. I'm very surprised that Brave would decide to require Google services to function.
This is in addition to being exclusively available on the Google Play Store, if you don't have it, you need to use alternative play store clients like Amaze or Yalp or resort to downloading APKs from websites (questionable or not). A apk download on the website and built-in auto-updater would be very nice.

**Comment by brainscar** [comment]
I'm having the same issue, it just keeps spinning forever.

![brave](https://user-images.githubusercontent.com/38463143/62441738-2af89180-b70a-11e9-8f28-e067a3c8b497.gif)

**Comment by srirambv** [comment]
cc: @anthonypkeane @EyanGoldman @SergeyZhukovsky to take a call on this to close the issue. Lineage OS doesn't allow GPS to run to perform safetynet check so this would always fail.

**Comment by kravietz** [comment]
@srirambv the whole point of using LineageOS and other de-googled Android distros is specifically *not* to use Google Play Services, SafetyNet etc. I don't think Brave should be depending on this proprietary technology. If it needs curent location, it can ask for this permission explicitly.

**Comment by brainscar** [comment]
@srirambv why close an issue when it's not resolved? I thought one of the goals of brave was privacy features. Now you're basically saying that the most privacy enabled rom isn't welcome at brave.

**Comment by srirambv** [comment]
cc: @tomlowenthal

**Comment by brainscar** [comment]
@srirambv did you notice that there are 2 people talking to you? A bit strange that, as a collaborator, you're reaction is to ignore us and keep cc'ing people hoping that they will close the thread for you.

What about a constructive conversation about the actual problem here? People with lineage can't use Brave Rewards. That seems worthy of a discussion to me.

**Comment by brainscar** [comment]
@kravietz @jjakob here's a temporary fix that worked for me:

- remove brave
- install 1.0.89 (old version)
- go to chrome://flags
- search for (and enable) #enable-brave-rewards
- create wallet
- upgrade to latest version.

Now it works for me:

![brave-working](https://user-images.githubusercontent.com/38463143/62504123-fa693400-b7ab-11e9-8b50-ebb2145aed5c.jpg)

**Comment by tomlowenthal** [comment]
Hey y'all, before talking about the technical issue here, I'd like to ask that everyone avoid directly hassling folks at Brave who are just doing their jobs. @srirambv worked out what the underlying issue was, noticed that it wasn't his call to decide on a plan to resolve it, and tagged in the people who should evaluate and decide on a course of action. Please don't give him a hard time for doing that.

I appreciate the need to express the details of technical issues, and to articulate that you would like features to work a certain way. Those are all well within the scope of this forum. Harassing people is not.

* * * * *

On to the matter at hand. For better or worse, Brave Rewards for Android relies on SafetyNet right now. That was an expedient decision based the need for certain anti-fraud features we knew SafetyNet could provide. We know that this is an imperfect approach, and we're evaluating designs which are more effective with less unwanted breakage. In the mean time, this means that Rewards only works on certain Android devices. We're working on more elegant solutions.

With all that context, there is an additional bug here. If the SafetyNet check fails, Brave should report that Rewards is not available (as in [comment #2](https://github.com/brave/browser-android-tabs/issues/1865#issuecomment-512719222)), not just hang forever. We should fix that.

**Comment by evq** [comment]
@brainscar FYI while you may be able to see ads with this workaround you will not be able to be paid for them

**Comment by brainscar** [comment]
@evq thank you. Good to know.

@tomlowenthal I take harassment very serious. Because of that, after reading your comment, I thoroughly went over this thread, and could not find any traces of harassment. If you would be so kind, would you kindly point out specific harassment? 

I would like to correct it if it's something I said or if I in any way shape or form made @srirambv feel unwelcome, upset or hurt. 

If you rather won't, that is perfectly fine too, but then please refrain from making these accusations of harassment. We are all adults here and I'm sure nobody in this thread appreciates being falsely accused of engaging in harassment. One might argue that such slander is harassment in itself.

Thank you.

**Comment by tomlowenthal** [comment]
@brainscar I am referring to your comments directed at Sri. You specifically challenge him for tagging in other people rather than engaging in a debate with you. Don't do that. Also: this comment isn't an opening to have a discussion about it. Further conversation about this is off topic.

**Comment by kravietz** [comment]
@tomlowenthal 

> We know that this is an imperfect approach

That is "we can do better than Google but we rely on Google so we cannot" approach really. 

> this means that Rewards only works on certain Android devices

This means Rewards works only on Google-enabled devices, which means that even if you switch to Brave you continue to feed Google with your tracking data.

I really like the idea of Rewards but making it dependent on Google services is a fundamental contradiction in your philosophy.
