### ISSUE TITLE
Failed to download third party dependencies

### ISSUE THREAD

**Issue by 4ntoine** [brave/browser-android-tabs#216]
while executing `sh scripts/getThirdParties.js` i'm getting error:

```
________ running 'download_from_google_storage --no_resume --platform=linux* --extract --no_auth --bucket chromium-nodejs/6.9.4 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' in '/home/asmirnov/browser-android-tabs'
Traceback (most recent call last):
  File "/home/asmirnov/depot_tools/download_from_google_storage.py", line 538, in <module>
    sys.exit(main(sys.argv))
  File "/home/asmirnov/depot_tools/download_from_google_storage.py", line 534, in main
    options.extract)
  File "/home/asmirnov/depot_tools/download_from_google_storage.py", line 358, in download_from_google_storage
    ignore_errors, output, sha1_file, auto_platform)
  File "/home/asmirnov/depot_tools/download_from_google_storage.py", line 152, in enumerate_work_queue
    raise FileNotFoundError('%s not found.' % input_filename)
__main__.FileNotFoundError: src/third_party/node/linux/node-linux-x64.tar.gz.sha1 not found.
Error: Command 'download_from_google_storage --no_resume --platform=linux* --extract --no_auth --bucket chromium-nodejs/6.9.4 -s src/third_party/node/linux/node-linux-x64.tar.gz.sha1' returned non-zero exit status 1 in /home/asmirnov/browser-android-tabs

```

**Comment by 4ntoine** [comment]
Ubuntu 16.04.2 LTS

**Comment by SergeyZhukovsky** [comment]
@4ntoine sorry for the long response. Could you please try it again, I fixed that yesterday.
