### ISSUE TITLE
Browser-android-tabs based browser crashes when ad notification is shown.

### ISSUE THREAD

**Issue by gdregalo** [brave/browser-android-tabs#2543]
## Description 
Browser-android-tabs based browser crashes when ad notification is shown.
Similar issue for android-core: https://github.com/brave/brave-core/pull/4533.
But it's not applicable for Browser-android-tabs . 

Crash stack:

    java.lang.IllegalArgumentException: Could not parse: chrome://brave_ads/
        at org.chromium.chrome.browser.browserservices.Origin.createOrThrow(Origin.java:93)
        at org.chromium.chrome.browser.browserservices.Origin.createOrThrow(Origin.java:85)
        at org.chromium.chrome.browser.settings.website.SingleWebsitePreferences.createFragmentArgsForSite(SingleWebsitePreferences.java:163)
        at org.chromium.chrome.browser.notifications.NotificationPlatformBridge.buildNotification(NotificationPlatformBridge.java:668)
        at org.chromium.chrome.browser.notifications.NotificationPlatformBridge.displayNotificationInternal(NotificationPlatformBridge.java:552)
        at org.chromium.chrome.browser.notifications.NotificationPlatformBridge.lambda$displayNotification$0$NotificationPlatformBridge(NotificationPlatformBridge.java:503)
        at org.chromium.chrome.browser.notifications.NotificationPlatformBridge$$Lambda$0.onResult(Unknown Source:50)
        at org.chromium.base.Promise.lambda$postCallbackToLooper$3$Promise(Promise.java:293)
        at org.chromium.base.Promise$$Lambda$5.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6854)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

## Steps to reproduce 

   1.  Install C80 based browser.
   2. Enable rewards and wait for the first ad notification.
   3. Observe the app is crashing.

## Issue happens on 
   - Current Play Store version?
   - Beta build?

## Device details
   - Install type (ARM, x86):
   - Device (Phone, Tablet, Phablet):
   - Android version:
   
### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by btlechowski** [comment]
Verification passed on BraveModernarm v1.5.6-rc1 on Samsung Galaxy Tab S5e (Android 9.0). The app does not crash when notification is shown. No crash when clicking on the notification. Tested on 4 ads.
